# Generated by Django 3.2.4 on 2022-07-19 21:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('delete', 'Delete')], db_index=True, default='draft', verbose_name='status')),
                ('category', models.TextField(choices=[('hot', 'Hot'), ('cold', 'Cold'), ('bagle', 'Bagle'), ('others', 'Others')], db_index=True, default='others', max_length=20, verbose_name='category')),
                ('name', models.TextField(db_index=True, max_length=120, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
